# .pre-commit-config.yaml file for https://github.com/jbouwh/incomfort-client

repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        files: ^(incomfort.*/.+)?[^/]+\.py$

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings==1.6.0
          - pydocstyle==6.2.3
        files: ^incomfort.*/.+\.py$
        exclude: ^incomfort.*/tests\.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: local
    hooks:
      - id: pylint
        name: 🌟 Starring code with pylint
        language: system
        types: [python]
        entry: poetry run pylint
