# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.6

    working_directory: ~/repo

    environment:
      # TEST_RESULTS=/tmp/test-results; mkdir -p ${TEST_RESULTS}
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run: mkdir -p $TEST_RESULTS

      - run:
          name: App response
          no_output_timeout: 30
          command: |
            . venv/bin/activate
            python inclient.py ${GATEWAY} | \
              tee ${TEST_RESULTS}/response_app.json

      - run:
          name: App response (rooms)
          no_output_timeout: 30
          command: |
            . venv/bin/activate
            sed '/^ *if _value/  s/is not None/!= 99/' incomfortclient/__init__.py \
              > ${TEST_RESULTS}/__init__.py
            python ${TEST_RESULTS}/__init__.py ${GATEWAY} \
              | tee -a ${TEST_RESULTS}/response_app_rooms.json

      - run:
          name: App response (raw)
          no_output_timeout: 30
          command: |
            . venv/bin/activate
            python inclient.py ${GATEWAY} --raw \
              | tee ${TEST_RESULTS}/response_app_raw.json

      - run:
          name: cURL response (raw)
          no_output_timeout: 30
          command: |
            curl -X GET http://${GATEWAY}/data.json?heater=0 | \
              python -c "import sys, json; print(json.load(sys.stdin))" | \
              tee ${TEST_RESULTS}/response_curl_raw.json

      - run:
          name: Compare cURL vs App (raw)
          no_output_timeout: 30
          command: |
            echo diff -s ${TEST_RESULTS}/response_curl_raw.json ${TEST_RESULTS}/response_app_raw.json | \
              tee -a ${TEST_RESULTS}/test-results.txt
            diff -s ${TEST_RESULTS}/response_curl_raw.json ${TEST_RESULTS}/response_app_raw.json | \
              tee -a ${TEST_RESULTS}/test-results.txt
            echo tee -a ${TEST_RESULTS}/test-results.txt

      - store_artifacts:
          path: /tmp/test-results
          destination: devices_summary
