# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # TEST_RESULTS=/tmp/test-results; mkdir -p ${TEST_RESULTS}
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io

      - run: mkdir -p $TEST_RESULTS

      - run:
          name: cURL response
          no_output_timeout: 30
          command: |
            curl -X GET http://cr-router.bonnes.me/data.json?heater=0 | \
              python -c "import sys, json; print(json.load(sys.stdin))" | \
              tee ${TEST_RESULTS}/response_curl.json

      - run:
          name: App response (raw)
          no_output_timeout: 30
          command: |
            . venv/bin/activate
            python intouchclient/__init__.py cr-router.bonnes.me --raw | \
              python -c "import sys, json; print(json.load(sys.stdin))" | \
              tee ${TEST_RESULTS}/response_app_raw.json

      - run:
          name: Compare cURL vs App
          no_output_timeout: 30
          command: |
            echo diff -s ${TEST_RESULTS}/response_curl.json ${TEST_RESULTS}/response_app_raw.json | tee -a ${TEST_RESULTS}/test-results.txt
                 diff -s ${TEST_RESULTS}/response_curl.json ${TEST_RESULTS}/response_app_raw.json | tee -a ${TEST_RESULTS}/test-results.txt
            echo                                                                                  | tee -a ${TEST_RESULTS}/test-results.txt

      - run:
          name: App response
          no_output_timeout: 30
          command: |
            . venv/bin/activate
            python intouchclient/__init__.py cr-router.bonnes.me | \
              tee ${TEST_RESULTS}/response_app.json

      - store_artifacts:
          path: /tmp/test-results
          destination: devices_summary
